package org.jboss.quickstarts.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class CustomerType  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String type;

    public CustomerType() {
    }

    public CustomerType(java.lang.String type) {
        this.type = type;
    }


    
    public java.lang.String getType() {
        return this.type;
    }

    public void setType(  java.lang.String type ) {
        this.type = type;
    }
}