package org.jboss.quickstarts.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Sale  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Boolean approved;
    
    @org.kie.api.definition.type.Position(value = 0)
    private org.jboss.quickstarts.brms.Customer customer;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Double discount;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.math.BigDecimal value;

    public Sale() {
    }

    public Sale(org.jboss.quickstarts.brms.Customer customer, java.math.BigDecimal value, java.lang.Double discount, java.lang.Boolean approved) {
        this.customer = customer;
        this.value = value;
        this.discount = discount;
        this.approved = approved;
    }


    
    public java.lang.Boolean getApproved() {
        return this.approved;
    }

    public void setApproved(  java.lang.Boolean approved ) {
        this.approved = approved;
    }
    
    public org.jboss.quickstarts.brms.Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(  org.jboss.quickstarts.brms.Customer customer ) {
        this.customer = customer;
    }
    
    public java.lang.Double getDiscount() {
        return this.discount;
    }

    public void setDiscount(  java.lang.Double discount ) {
        this.discount = discount;
    }
    
    public java.math.BigDecimal getValue() {
        return this.value;
    }

    public void setValue(  java.math.BigDecimal value ) {
        this.value = value;
    }
}