package org.jboss.quickstarts.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Salesman extends org.jboss.quickstarts.brms.Person implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.util.List<org.jboss.quickstarts.brms.Sale> allSales;

    public Salesman() {
    }

    public Salesman(java.util.List<org.jboss.quickstarts.brms.Sale> allSales) {
        this.allSales = allSales;
    }


    
    public java.util.List<org.jboss.quickstarts.brms.Sale> getAllSales() {
        return this.allSales;
    }

    public void setAllSales(  java.util.List<org.jboss.quickstarts.brms.Sale> allSales ) {
        this.allSales = allSales;
    }
}