package org.jboss.quickstarts.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class CarProfile  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Boolean hasAlarm;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Boolean hasGarage;

    public CarProfile() {
    }

    public CarProfile(java.lang.Boolean hasAlarm, java.lang.Boolean hasGarage) {
        this.hasAlarm = hasAlarm;
        this.hasGarage = hasGarage;
    }


    
    public java.lang.Boolean getHasAlarm() {
        return this.hasAlarm;
    }

    public void setHasAlarm(  java.lang.Boolean hasAlarm ) {
        this.hasAlarm = hasAlarm;
    }
    
    public java.lang.Boolean getHasGarage() {
        return this.hasGarage;
    }

    public void setHasGarage(  java.lang.Boolean hasGarage ) {
        this.hasGarage = hasGarage;
    }
}