package org.jboss.quickstarts.brms;

import java.util.Calendar;
import java.util.Date;

function int getAge(Date birthDate){
      Calendar dob = Calendar.getInstance();
      dob.setTime(birthDate);
      Calendar today = Calendar.getInstance();
      int age = today.get(Calendar.YEAR) - dob.get(Calendar.YEAR);
      if (today.get(Calendar.DAY_OF_YEAR) <= dob.get(Calendar.DAY_OF_YEAR)){
		age--;
      }
      return age;
}
